#!/bin/sh
set -efu

pys="$(py3versions -r 2>/dev/null)"

cd "$ADTTMP"

for py in $pys; do
    echo "=== $py ==="
    $py /usr/bin/nosetests3 -v zmq.tests 2>&1
    echo "=== $py-dbg ==="
    $py-dbg /usr/bin/nosetests3 -v zmq.tests 2>&1
done
