#!/bin/sh
set -efu

pys="$(pyversions -r 2>/dev/null)"

cd "$ADTTMP"

for py in $pys; do
    echo "=== $py ==="
    $py /usr/bin/nosetests -v zmq.tests 2>&1
    echo "=== $py-dbg ==="
    $py-dbg /usr/bin/nosetests -v zmq.tests 2>&1
done
